server:
  port: 8002

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xukenantop.mysql.rds.aliyuncs.com:33066/clouddemo2021?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&useInformationSchema=true
    username: conan
    password: Xukenan11

mybatis-plus:
  configuration:
    autoMappingBehavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    object-wrapper-factory: com.baomidou.mybatisplus.extension.MybatisMapWrapperFactory

